spring:
  application:
    name: driveshare-backend
  profiles:
    active: dev

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
